#! /bin/sh

# pubsubplus-opentelemetry-go-integration
#
# Copyright 2024 Solace Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Removes previously generated SEMPv2 client code from ./action, ./config and
# ./monitor, leaving the committed go.mod / go.sum in each directory intact.
# Runs on the host (via `go generate`) and must stay POSIX sh: /bin/sh is dash
# on the Linux build agents and bash on macOS.

BASEDIR=$(cd "$(dirname "$0")" && pwd)

cleanup_files() {
    echo "from $(pwd) cleanup $*"
    rm -rf "$@"
}

cleanup() {
    echo "script dir $BASEDIR"
    gen_dirs="action config monitor"
    sub_gen_dirs=".swagger-codegen* docs api"
    gen_files="*.go *.sh *.md *.yml .gitignore .*.yml"

    for topdir in $gen_dirs ; do
        cur_dir="$BASEDIR/$topdir"
        if [ -e "$cur_dir" ]; then
            (cd "$cur_dir" && cleanup_files $sub_gen_dirs) && (cd "$cur_dir" && cleanup_files $gen_files)
        fi
    done
}

cleanup "$@"
